import { TwSizeIndicator } from '@repo/ui/components/core/tw-sizeIndicator';
import '@repo/ui/main.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Docs',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TwSizeIndicator />
        {children}
      </body>
    </html>
  );
}
